In [1]:
from typing import Union, Optional, List, Tuple, Dict, Any, Iterable, TypeVar, Type, NamedTuple, Sequence, Generic, _GenericAlias

from beartype import beartype
from edf_interface.data.se3 import SE3
from edf_interface.data.pointcloud import PointCloud

import torch

In [2]:
poses = SE3(poses=torch.tensor([[1., 0., 0., 0., 0., 0., 1.]])).to('cuda')
print(poses)

<SE3 (cuda:0)>
  Metadata: 
    - name: 
  Data: 
    - poses: <Tensor> (Shape: torch.Size([1, 7]))
          tensor([[1., 0., 0., 0., 0., 0., 1.]], device='cuda:0')



In [3]:
print(SE3.from_data_dict(poses.get_data_dict(), device='cpu'))

<SE3>
  Metadata: 
    - name: 
  Data: 
    - poses: <Tensor> (Shape: torch.Size([1, 7]))
          tensor([[1., 0., 0., 0., 0., 0., 1.]])



In [4]:
pcd = PointCloud(points = torch.randn(5,3), colors = torch.randn(5,3), name='pcd_test').to('cuda')
print(pcd)

<PointCloud (cuda:0)>
  Metadata: 
    - name: pcd_test
  Data: 
    - points: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 0.2705, -0.8222,  0.7405],
                  [-1.4753,  0.9671,  0.4145],
                  [ 0.2036,  0.5835,  0.0837],
                  [ 0.0025, -0.5326,  1.8675],
                  [-0.5537,  1.3781,  1.3210]], device='cuda:0')
    - colors: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 1.0019,  0.1771, -0.0932],
                  [ 0.0876,  0.6277, -1.3474],
                  [-0.5938,  1.2340,  0.4208],
                  [-0.3308,  0.7828,  1.8231],
                  [ 1.4777, -0.5799,  0.1459]], device='cuda:0')



In [5]:
print(PointCloud.from_data_dict(pcd.get_data_dict(), device='cpu'))

<PointCloud>
  Metadata: 
    - name: pcd_test
  Data: 
    - points: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 0.2705, -0.8222,  0.7405],
                  [-1.4753,  0.9671,  0.4145],
                  [ 0.2036,  0.5835,  0.0837],
                  [ 0.0025, -0.5326,  1.8675],
                  [-0.5537,  1.3781,  1.3210]])
    - colors: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 1.0019,  0.1771, -0.0932],
                  [ 0.0876,  0.6277, -1.3474],
                  [-0.5938,  1.2340,  0.4208],
                  [-0.3308,  0.7828,  1.8231],
                  [ 1.4777, -0.5799,  0.1459]])

