In [1]:
from typing import Union, Optional, List, Tuple, Dict, Any, Iterable, TypeVar, Type, NamedTuple, Sequence, Generic, _GenericAlias

from beartype import beartype
from edf_interface.data.se3 import SE3
from edf_interface.data.pointcloud import PointCloud

import torch

In [2]:
poses = SE3(poses=torch.tensor([[1., 0., 0., 0., 0., 0., 1.]])).to('cuda')
poses

<SE3>  (device: cuda:0)
  Metadata: 
    - name: ''
  Data: 
    - poses: <Tensor> (Shape: torch.Size([1, 7]))
          tensor([[1., 0., 0., 0., 0., 0., 1.]], device='cuda:0')

In [3]:
SE3.from_data_dict(poses.get_data_dict(), device='cpu')

<SE3>  (device: cpu)
  Metadata: 
    - name: ''
  Data: 
    - poses: <Tensor> (Shape: torch.Size([1, 7]))
          tensor([[1., 0., 0., 0., 0., 0., 1.]])

In [4]:
pcd = PointCloud(points = torch.randn(5,3), colors = torch.randn(5,3), name='pcd_test').to('cuda')
pcd

<PointCloud>  (device: cuda:0)
  Metadata: 
    - name: 'pcd_test'
  Data: 
    - points: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 0.2477, -1.7461, -0.9074],
                  [-0.3862, -0.8556, -0.2189],
                  [-2.1966, -0.4229, -0.1750],
                  [ 0.4268,  1.3004, -0.7944],
                  [ 0.4193,  0.5747,  0.7027]], device='cuda:0')
    - colors: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 1.9527,  2.0025,  2.1180],
                  [ 0.1574,  0.9105, -1.4870],
                  [ 0.7916,  0.6783, -1.6962],
                  [ 0.2659, -0.3983, -1.2454],
                  [-0.7042,  1.0268,  1.3544]], device='cuda:0')

In [5]:
PointCloud.from_data_dict(pcd.get_data_dict(), device='cpu')

<PointCloud>  (device: cpu)
  Metadata: 
    - name: 'pcd_test'
  Data: 
    - points: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 0.2477, -1.7461, -0.9074],
                  [-0.3862, -0.8556, -0.2189],
                  [-2.1966, -0.4229, -0.1750],
                  [ 0.4268,  1.3004, -0.7944],
                  [ 0.4193,  0.5747,  0.7027]])
    - colors: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 1.9527,  2.0025,  2.1180],
                  [ 0.1574,  0.9105, -1.4870],
                  [ 0.7916,  0.6783, -1.6962],
                  [ 0.2659, -0.3983, -1.2454],
                  [-0.7042,  1.0268,  1.3544]])