In [1]:
from typing import Union, Optional, List, Tuple, Dict, Any, Iterable, TypeVar, Type, NamedTuple, Sequence, Generic, _GenericAlias

from beartype import beartype
from edf_interface.data.se3 import SE3
from edf_interface.data.pointcloud import PointCloud

import torch

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
data = SE3(poses=torch.tensor([[1., 0., 0., 0., 0., 0., 1.]])).to('cuda')
data

<SE3>  (device: cuda:0)
  Metadata: 
    - name: ''
  Data: 
    - poses: <Tensor> (Shape: torch.Size([1, 7]))
          tensor([[1., 0., 0., 0., 0., 0., 1.]], device='cuda:0')

In [3]:
pcd = PointCloud(points = torch.randn(5,3), colors = torch.randn(5,3), name='pcd_test').to('cuda')
pcd

<PointCloud>  (device: cuda:0)
  Metadata: 
    - name: 'pcd_test'
  Data: 
    - points: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[-1.2508,  2.0523, -0.6877],
                  [-2.0557, -0.7006, -1.2304],
                  [ 0.8561, -0.7267, -0.3047],
                  [ 1.9229,  0.4273,  1.6932],
                  [-0.2823,  1.3141,  1.1878]], device='cuda:0')
    - colors: <Tensor> (Shape: torch.Size([5, 3]))
          tensor([[ 0.2226,  0.4242, -0.9154],
                  [ 1.1867,  0.6271, -0.1748],
                  [ 0.0368, -2.1644,  0.5762],
                  [ 2.2487, -0.9565,  0.2786],
                  [ 1.6299, -0.1775, -0.3001]], device='cuda:0')